#name: Update vv ita world
#on:
#  schedule:
#    - cron: '0 */6 * * *'  # Esegue ogni 6 ore
#  workflow_dispatch:  # Permette di eseguire manualmente
#
#permissions:
#  contents: write  # Permette di fare commit e push nel repository
#
#jobs:
#  run-script:
#    runs-on: ubuntu-latest
#    concurrency:
#      group: ${{ github.workflow }}-${{ github.ref }}
#      cancel-in-progress: false
#    
#    steps:
#      - name: Checkout del repository
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0  # Modificato da 1 a 0 per ottenere la storia completa
#      - name: Imposta Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.x'  # Sostituisci con la versione necessaria
#
#      - name: Installa le dipendenze
#        run: pip install requests
#
#      - name: Esegui lo script
#        run: |
#          python def.py
#          python vvworld.py
#          
#      - name: Commit and push changes
#        run: |
#          git config --global user.name "actions-user"
#          git config --global user.email "actions@github.com"
#          
#          # Ignore Python bytecode files to avoid binary conflicts
#          echo "__pycache__/" >> .gitignore
#          echo "*.pyc" >> .gitignore
#          
#          # Stage all changes
#          git add .
#          
#          # Check if there are changes to commit
#          if [[ -n $(git status --porcelain) ]]; then
#            # Commit changes
#            git commit -m "Update VV ita wrld $(date +%H:%M)"
#            
#            # Force push to avoid merge conflicts
#            git push --force origin HEAD:main
#          else
#            echo "No changes to commit"
#          fi
